# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-03-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0034_version_channels'),
    ]

    operations = {
        # Remove the old `channel` field. You may need to manually delete
        # versions with duplicate (app, platform, version) first. This can
        # happen if they have different channels. Ideally, they will have the
        # same file_hash. When this comment was written, there was just one such
        # duplicate version in the production database.
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('app', 'platform', 'version')},
        ),
        migrations.AlterIndexTogether(
            name='version',
            index_together={('app', 'platform', 'version')},
        ),
        migrations.RemoveField(
            model_name='version',
            name='channel',
        )

    }
