# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-04-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import omaha.models
import omaha_server.s3utils


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0035_remove_version_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Channel'),
        )
    ]
