# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-04-20 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0036_longer_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
