# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-06-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0038_version_file_sha256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
