# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-06-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0040_allowed_user_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='allowed_user_ids',
            new_name='allowed_oem_ids',
        ),
        migrations.AlterField(
            model_name='version',
            name='allowed_oem_ids',
            field=models.TextField(blank=True, help_text='Separated by line breaks. If empty, all devices have access.', verbose_name='Allowed device OEM IDs'),
        )
    ]
