# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-10-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import omaha.models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0041_rename_allowed_user_ids_to_allowed_oem_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialupdate',
            name='channels',
            field=models.ManyToManyField(db_index=True, default=omaha.models._prod_channel, to='omaha.Channel'),
        )
    ]
